In [1]:
# UFUNCS: uNIVERSAL FUNCTIONS

import numpy as np

# Array addition
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
print(np.add(x,y))

print("\n")
# Create your own ufuncs
def myadd(a,b):
    return a+b
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2],[3,4]))
print(type(myadd))

print("\n")
# Check if function is ufunc
print(type(np.concatenate))
print(type(np.add))
print(type(myadd))

print("\n")
# Simple arithmetic

# 1.Addition: add()
x=np.array([10,20,30,40])
y=np.array([1,2,3,4])
print(x)
print(y)
print(np.add(x,y))

print("\n")
# 2.Subtraction: subtract()
x=np.array([10,20,30,40])
y=np.array([1,2,3,4])
print(x)
print(y)
print(np.subtract(x,y))

print("\n")
# 3.Multiply: multiply()
x=np.array([10,20,30,40])
y=np.array([1,2,3,4])
print(x)
print(y)
print(np.multiply(x,y))

print("\n")
# 4.Divide: divide()
x=np.array([10,20,30,40])
y=np.array([2,5,8,8])
print(x)
print(y)
print(np.divide(x,y))

print("\n")
# 5.Power: power()
x=np.array([10,20,30,40])
y=np.array([1,2,3,4])
print(x)
print(y)
print(np.power(x,y))

print("\n")
# 6.Remainder: mod(),remainder()
x=np.array([10,20,30,40])
y=np.array([1,3,4,7])
print(x)
print(y)
print(np.mod(x,y))

print("\n")
x=np.array([10,20,30,40])
y=np.array([2,3,5,7])
print(x)
print(y)
print(np.remainder(x,y))

print("\n")
# 7.Quotient & mod: divmod()
x=np.array([10,20,30,40])
y=np.array([3,2,4,9])
print(x)
print(y)
print(np.divmod(x,y))

print("\n")
# 8.Absolute values: absolute() & abs()
x=np.array([10,-20,30,-45])
print(x)
print(np.absolute(x))



[ 5  7  9 11]


[4 6]
<class 'numpy.ufunc'>


<class 'builtin_function_or_method'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


[10 20 30 40]
[1 2 3 4]
[11 22 33 44]


[10 20 30 40]
[1 2 3 4]
[ 9 18 27 36]


[10 20 30 40]
[1 2 3 4]
[ 10  40  90 160]


[10 20 30 40]
[2 5 8 8]
[5.   4.   3.75 5.  ]


[10 20 30 40]
[1 2 3 4]
[     10     400   27000 2560000]


[10 20 30 40]
[1 3 4 7]
[0 2 2 5]


[10 20 30 40]
[2 3 5 7]
[0 2 0 5]


[10 20 30 40]
[3 2 4 9]
(array([ 3, 10,  7,  4], dtype=int32), array([1, 0, 2, 4], dtype=int32))


[ 10 -20  30 -45]
[10 20 30 45]


In [2]:
# Rounding decimals

# 1. Truncation: Trunc()/fix(), returns integer
x=np.array([-1.2558,2.9999,3.0002])
print(x)
print(np.trunc(x))
print(np.fix(x))

print("\n")
# 2. Rounding: around()
x=np.around(3.1666,2)
y=np.around(3.1666,1)
print(x)
print(y)
z=np.array([-1.2558,2.9999,3.0352])
print(z)
print(np.around(z,2))

print("\n")
# 3. Floor: floor(), returns float
x=np.array([-1.2558,2.9999,3.0352])
print(x)
print(np.floor(x))

print("\n")
# 4. Ceil: ceil()
x=np.array([-1.2558,2.9999,3.0352])
print(x)
print(np.ceil(x))


[-1.2558  2.9999  3.0002]
[-1.  2.  3.]
[-1.  2.  3.]


3.17
3.2
[-1.2558  2.9999  3.0352]
[-1.26  3.    3.04]


[-1.2558  2.9999  3.0352]
[-2.  2.  3.]


[-1.2558  2.9999  3.0352]
[-1.  3.  4.]


In [3]:
# Numpy Logs

x=np.arange(1,10)
print(x)

print("\n")
#Log at base 2
print(np.log2(x))

print("\n")
#log at base 10
print(np.log10(x))

print("\n")
#Natural log or Log at base e
print(np.log(x))

print("\n")
#Log at any base: Not provided by numpy, created by user
from math import log
nplog=np.frompyfunc(log,2,1)
print(nplog(100,15))


[1 2 3 4 5 6 7 8 9]


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


1.7005483074552052


In [4]:
# Numpy Summations

x = np.array([1, 2, 3])
print(np.sum(x))

y = np.array([4, 5, 6])
print(np.sum([x,y]))

print("\n")
# Summation over an axis
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.sum([x,y],axis=1))

print("\n")
# Cummulative sum
x = np.array([1, 2, 3])
print(np.cumsum(x))

6
21


[ 6 15]


[1 3 6]


In [5]:
# Numpy products

x = np.array([1, 2, 3])
print(np.prod(x))

y = np.array([4, 5, 6])
print(np.prod([x,y]))

print("\n")
# Product over an axis
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.prod([x,y],axis=1))

print("\n")
# Cummulative product
x = np.array([1, 2, 3])
print(np.cumprod(x))

6
720


[  6 120]


[1 2 6]


In [6]:
# Numpy Differences

x=np.array([15,10,5,25])
print(np.diff(x))

print("\n")
print(np.diff(x,2))
print(np.diff(x,3))

[-5 -5 20]


[ 0 25]
[25]


In [7]:
# Numpy LCM(Lowest Common Multiple)

print(np.lcm(4,6))

print("\n")
#LCM in Arrays
x=np.array([3,6,9])
print(np.lcm.reduce(x))


12


18


In [8]:
# Numpy GCD/HCF(Greatest common denominator/Highest common factor)

print(np.gcd(6,9))

print("\n")
# GCD in arrays
x=np.array([20,8,32,36,16])
print(np.gcd.reduce(x))

3


4


In [9]:
# Numpy trignometric functions: sin(),cos(),tan()

import numpy as np
print(np.sin(np.pi/2))
print(np.cos(np.pi/2))
print(np.tan(np.pi/2))

x=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

print("\n")
# Degree to radians & Radians to degress: deg2rad(),rad2deg

x=np.array([90,180,270,360])
y=np.deg2rad(x)
print(x)
print(y)
z=np.rad2deg(y)
print(z)

print("\n")
# Finding Angles: arcsin(),arccos(),arctan()
print(np.arcsin(1.0))
print(np.arccos(1.0))
print(np.arccos(1.0))

x=np.array([1,-1,0,0.1])
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

print("\n")
# Hypotenues: hypot()
base=3
perp=4
print(np.hypot(base,perp))



1.0
6.123233995736766e-17
1.633123935319537e+16
[1.         0.8660254  0.70710678 0.58778525]
[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]
[1.63312394e+16 1.73205081e+00 1.00000000e+00 7.26542528e-01]


[ 90 180 270 360]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


1.5707963267948966
0.0
0.0
[ 1.57079633 -1.57079633  0.          0.10016742]
[0.         3.14159265 1.57079633 1.47062891]
[ 0.78539816 -0.78539816  0.          0.09966865]


5.0


In [10]:
# Hyperbolic functions: sinh(),cosh(),tanh()

print(np.sinh(np.pi/2))
print(np.cosh(np.pi/2))
print(np.tanh(np.pi/2))

x=np.array([np.pi/2,np.pi/4,np.pi/6])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

print("\n")
# finding angles

print(np.arcsinh(1.0))
print(np.arccosh(2.0))
print(np.arctanh(0.3))

x=np.array([0.1,0.2,0.5])
print(np.arcsinh(x))
print(np.arccosh(x))
print(np.arctanh(x))

2.3012989023072947
2.5091784786580567
0.9171523356672744
[2.3012989  0.86867096 0.54785347]
[2.50917848 1.32460909 1.14023832]
[0.91715234 0.6557942  0.48047278]


0.881373587019543
1.3169578969248166
0.30951960420311175
[0.09983408 0.19869011 0.48121183]
[nan nan nan]
[0.10033535 0.20273255 0.54930614]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in arccosh


In [11]:
# Set operations: unique()

x=np.array([2,3,3,8,9,16,9,21])
y=np.unique(x)
print(x)
print(y)

print("\n")
# Finding union: union1d()
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])
print(x)
print(y)
print(np.union1d(x,y))

print("\n")
#Finding Intersection: intersection1d()
print(x)
print(y)
print(np.intersect1d(x,y))
print(np.intersect1d(x,y,assume_unique=True))

print("\n")
# Finding Difference: setdiff1d()
print(x)
print(y)
print(np.setdiff1d(x,y))
print(np.setdiff1d(x,y,assume_unique=True))

print("\n")
# Symmetric Difference: setxor1d()
print(x)
print(y)
print(np.setxor1d(x,y))
print(np.setxor1d(x,y,assume_unique=True))


[ 2  3  3  8  9 16  9 21]
[ 2  3  8  9 16 21]


[1 2 3 4]
[3 4 5 6]
[1 2 3 4 5 6]


[1 2 3 4]
[3 4 5 6]
[3 4]
[3 4]


[1 2 3 4]
[3 4 5 6]
[1 2]
[1 2]


[1 2 3 4]
[3 4 5 6]
[1 2 5 6]
[1 2 5 6]
